### ISSUE TITLE
issue with range()

### ISSUE THREAD

**Issue by avest** [adhocore/php-cron-expr#12]
There is an issue with the range() call in Validator.php.

you will get an error if you run:
Expression::isDue('5/20 * * * *', '2018-08-13 00:24:00');

Here is my fix:

	public function inStep($value, $offset)
	{
		if (\strpos($offset, '*/') !== false || \strpos($offset, '0/') !== false)
		{
			$parts = \explode('/', $offset, 2);

			return $value % $parts[1] === 0;
		}

		$parts = \explode('/', $offset, 2);

		$subparts = \explode('-', $parts[0], 2) + [1 => $value];

		$range_start = $subparts[0];

		$range_end = $subparts[1];

		$range_step = $parts[1];

		$range_max = $range_start + $range_step;

		$range = array($range_start);
		if ($range_end >= $range_max)
		{
			$range = \range($subparts[0], $subparts[1], $parts[1]);
		}

		$in_range = false;
		if ($range)
		{
			$in_range = \in_array($value, $range);
		}

		//return ($subparts[0] <= $value && $value <= $subparts[1] && $parts[1])
		//	? \in_array($value, \range($subparts[0], $subparts[1], $parts[1]))
		//	: false;
		return ($subparts[0] <= $value && $value <= $subparts[1] && $parts[1])
			? $in_range
			: false;
	}

**Comment by avest** [comment]
Turns out when I test "5/20 * * * *" as a real cron job, it doesn't actually kick off a job, "5-45/20 * * * *" does.  So, probably not a valid expression...

**Comment by adhocore** [comment]
thanks for filing issue. will take a look later today. 😊

**Comment by adhocore** [comment]
fixed. and bulk checks added too. maybe bump version in your `composer.json` (something like "adhocore/cron-expr": "^0.0") then `$ composer update` should be fine
